jobs:
  include:
    - stage: test bus
      language: node_js
      node_js:
        - "stable"
      before_install: cd $TRAVIS_BUILD_DIR/bus
      install:
        - npm install
    - stage: test driver
      language: node_js
      node_js:
        - "stable"
      before_install: cd $TRAVIS_BUILD_DIR/driver
      install:
        - npm install
    - stage: test schedule
      language: node_js
      node_js:
        - "stable"
      before_install: cd $TRAVIS_BUILD_DIR/driver
      install:
        - npm install
    - stage: test gateway
      language: node_js
      node_js:
        - "stable"
      before_install: cd $TRAVIS_BUILD_DIR/gateway
      install:
        - npm install

      
      